services:
  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: angular-app
    mem_limit: 4g
    ports:
      - "${PORT:-4200}:4200"
    volumes:
      - .:/app
    environment:
      - NG_CLI_ANALYTICS=false
    command: ng serve --host 0.0.0.0 --poll 2000
    stdin_open: true
    tty: true
